# Generated by Django 5.2.7 on 2025-11-15 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_kudipoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_review_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='KudiPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent_ghs', models.DecimalField(decimal_places=2, default=0, help_text='Total purchases on Kudiway (GHS).', max_digits=10)),
                ('followers_count', models.PositiveIntegerField(default=0, help_text='Social media followers.')),
                ('avg_engagement', models.PositiveIntegerField(default=0, help_text='Average likes/comments/views per post.')),
                ('primary_platform', models.CharField(blank=True, help_text='Platform: Instagram / TikTok / YouTube', max_length=50)),
                ('social_handle', models.CharField(blank=True, help_text='@username or profile link', max_length=100)),
                ('has_video_review', models.BooleanField(default=False, help_text='Has posted at least one Kudiway product review video.')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('requirements_met', models.BooleanField(default=False, help_text='Auto true when ₵500+ spent, 1000 followers, + verified review.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kudi_partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('tiktok_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('video_review_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
