# Generated by Django 5.2.7 on 2025-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_social_followers_profile_video_review_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='partner_application_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
