# Generated by Django 5.2.7 on 2025-11-16 22:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_partner_application_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_media_handle',
            field=models.CharField(blank=True, help_text='Handle or profile link (e.g., @gideonadams).', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media_platform',
            field=models.CharField(blank=True, choices=[('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('YouTube', 'YouTube'), ('Snapchat', 'Snapchat'), ('X', 'X (Twitter)'), ('Other', 'Other')], help_text='Primary social media platform used to promote Kudiway.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kudipartner',
            name='primary_platform',
            field=models.CharField(blank=True, help_text='Platform: Instagram / TikTok / YouTube, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='kudipartner',
            name='requirements_met',
            field=models.BooleanField(default=False, help_text='True when ₵500+ spent, 1000+ followers, and verified review.'),
        ),
        migrations.AlterField(
            model_name='kudipartner',
            name='social_handle',
            field=models.CharField(blank=True, help_text='@username or profile link.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_followers',
            field=models.IntegerField(default=0, help_text='Total followers on primary social account.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='video_review_links',
            field=models.JSONField(blank=True, default=list, help_text='List of URLs to product review videos.', null=True),
        ),
    ]
