# Generated by Django 5.2.7 on 2025-10-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0002_rename_credit_balance_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
