# Generated by Django 5.2.7 on 2025-10-08 20:14

import django.db.models.deletion
import kudiwallet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0005_kyc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_number',
            field=models.CharField(default='Unknown', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to=kudiwallet.models.kyc_upload_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to=kudiwallet.models.kyc_upload_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=kudiwallet.models.kyc_upload_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL),
        ),
    ]
