# Generated by Django 5.2.7 on 2025-10-10 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0006_kyc_full_name_kyc_id_number_kyc_id_type_kyc_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='reviewed_at',
        ),
        migrations.AlterField(
            model_name='kyc',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/id_backs/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/id_fronts/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
