# Generated by Django 5.2.7 on 2025-10-10 03:57

import kudiwallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0007_remove_kyc_remarks_remove_kyc_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to=kudiwallet.models.kyc_upload_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to=kudiwallet.models.kyc_upload_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Driver’s License', 'Driver’s License'), ('National ID', 'National ID'), ('Voter ID', 'Voter ID')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=kudiwallet.models.kyc_upload_path),
        ),
    ]
