# Generated by Django 5.2.7 on 2025-10-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0008_kyc_remarks_alter_kyc_id_back_alter_kyc_id_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('borrow', 'Borrow'), ('repay', 'Repay'), ('transfer', 'Transfer'), ('credit_purchase', 'Credit Purchase')], max_length=20),
        ),
    ]
