# Generated by Django 5.2.7 on 2025-10-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0009_kyc_reviewed_at_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='credit_score',
            field=models.PositiveIntegerField(default=600),
        ),
    ]
