# Generated by Django 5.2.7 on 2025-10-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0010_wallet_credit_limit_wallet_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('borrow', 'Borrow'), ('repay', 'Repay'), ('transfer', 'Transfer'), ('credit_purchase', 'Credit Purchase'), ('limit_increase', 'Limit Increase')], max_length=20),
        ),
    ]
