# Generated by Django 5.2.7 on 2025-10-25 01:10

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0011_alter_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('due_date', models.DateField(default=datetime.datetime(2025, 11, 8, 1, 10, 33, 87435, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_purchases', to='kudiwallet.wallet')),
            ],
        ),
    ]
