# Generated by Django 5.2.7 on 2025-10-25 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0012_creditpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 8, 1, 21, 48, 604195, tzinfo=datetime.timezone.utc)),
        ),
    ]
