# Generated by Django 5.2.7 on 2025-10-25 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0014_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 8, 2, 1, 26, 853993, tzinfo=datetime.timezone.utc)),
        ),
    ]
