# Generated by Django 5.2.7 on 2025-10-26 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0015_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpurchase',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='item_name',
            field=models.CharField(default='Store Purchase', max_length=150),
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 9, 9, 25, 10, 928018, tzinfo=datetime.timezone.utc)),
        ),
    ]
