# Generated by Django 5.2.7 on 2025-10-26 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0016_creditpurchase_is_paid_creditpurchase_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 9, 15, 13, 25, 615172, tzinfo=datetime.timezone.utc)),
        ),
    ]
