# Generated by Django 5.2.7 on 2025-10-28 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0017_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 11, 20, 8, 17, 141405, tzinfo=datetime.timezone.utc)),
        ),
    ]
