# Generated by Django 5.2.7 on 2025-10-29 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0018_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 12, 3, 18, 35, 857531, tzinfo=datetime.timezone.utc)),
        ),
    ]
