# Generated by Django 5.2.7 on 2025-11-01 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0020_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 15, 3, 9, 11, 139641, tzinfo=datetime.timezone.utc)),
        ),
    ]
