# Generated by Django 5.2.7 on 2025-11-02 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0021_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 16, 23, 47, 26, 347604, tzinfo=datetime.timezone.utc)),
        ),
    ]
