# Generated by Django 5.2.7 on 2025-11-05 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0023_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 19, 17, 18, 23, 917087, tzinfo=datetime.timezone.utc)),
        ),
    ]
