# Generated by Django 5.2.7 on 2025-11-07 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0024_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 21, 14, 22, 22, 308257, tzinfo=datetime.timezone.utc)),
        ),
    ]
