# Generated by Django 5.2.7 on 2025-11-08 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0030_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 22, 18, 46, 16, 570236, tzinfo=datetime.timezone.utc)),
        ),
    ]
