# Generated by Django 5.2.7 on 2025-11-08 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0031_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 22, 18, 53, 40, 739968, tzinfo=datetime.timezone.utc)),
        ),
    ]
