# Generated by Django 5.2.7 on 2025-11-08 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0033_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 22, 19, 9, 47, 196690, tzinfo=datetime.timezone.utc)),
        ),
    ]
