# Generated by Django 5.2.7 on 2025-11-10 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0036_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 24, 1, 51, 16, 512771, tzinfo=datetime.timezone.utc)),
        ),
    ]
