# Generated by Django 5.2.7 on 2025-11-10 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0037_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 24, 17, 15, 54, 210140, tzinfo=datetime.timezone.utc)),
        ),
    ]
