# Generated by Django 5.2.7 on 2025-11-12 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0038_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 26, 15, 59, 29, 42322, tzinfo=datetime.timezone.utc)),
        ),
    ]
