# Generated by Django 5.2.7 on 2025-11-12 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0039_wallet_phone_number_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomoCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payer_id', models.CharField(blank=True, max_length=32, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 26, 16, 17, 51, 391976, tzinfo=datetime.timezone.utc)),
        ),
    ]
