# Generated by Django 5.2.7 on 2025-11-12 16:45

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0041_alter_creditpurchase_due_date_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 26, 16, 42, 3, 162075, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='momocallbacklog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='momocallbacklog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='momocallbacklog',
            name='payer_id',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='momocallbacklog',
            name='reference_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='momocallbacklog',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
