# Generated by Django 5.2.7 on 2025-11-15 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0042_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 29, 15, 39, 29, 296650, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Driver’s License', 'Driver’s License'), ('National ID', 'National ID'), ('Voter ID', 'Voter ID')], default='Passport', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
