# Generated by Django 5.2.7 on 2025-11-16 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0043_alter_creditpurchase_due_date_alter_kyc_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 30, 14, 59, 8, 333660, tzinfo=datetime.timezone.utc)),
        ),
    ]
