# Generated by Django 5.2.7 on 2025-11-16 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0044_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 30, 22, 38, 39, 156076, tzinfo=datetime.timezone.utc)),
        ),
    ]
