# Generated by Django 5.2.7 on 2025-11-21 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0046_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 5, 1, 10, 56, 661832, tzinfo=datetime.timezone.utc)),
        ),
    ]
