# Generated by Django 5.2.7 on 2025-11-26 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0048_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 10, 13, 26, 15, 524439, tzinfo=datetime.timezone.utc)),
        ),
    ]
