# Generated by Django 5.2.7 on 2025-11-26 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0049_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 10, 13, 39, 27, 464404, tzinfo=datetime.timezone.utc)),
        ),
    ]
