# Generated by Django 5.2.7 on 2025-11-27 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0050_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 11, 0, 21, 51, 680362, tzinfo=datetime.timezone.utc)),
        ),
    ]
