# Generated by Django 5.2.7 on 2025-11-28 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0055_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 12, 18, 11, 43, 858710, tzinfo=datetime.timezone.utc)),
        ),
    ]
