# Generated by Django 5.2.7 on 2025-12-16 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudiwallet', '0058_alter_creditpurchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 30, 18, 27, 38, 454413, tzinfo=datetime.timezone.utc)),
        ),
    ]
