# Generated by Django 5.2.7 on 2025-11-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreview',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
