# Generated by Django 5.2.7 on 2025-11-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_review_product_id'),
        ('reviews', '0002_videoreview_cloudinary_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoreview',
            name='product_id',
        ),
        migrations.AddField(
            model_name='videoreview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_reviews', to='orders.product'),
        ),
        migrations.AddField(
            model_name='videoreview',
            name='review_product_id',
            field=models.CharField(blank=True, help_text='Matches OrderItem.review_product_id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videoreview',
            name='thumbnail_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Timestamp used when generating thumbnail', null=True),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam / Advertising'), ('nudity', 'Nudity or sexual content'), ('violence', 'Violence / Harmful content'), ('fraud', 'Fraud / Scam'), ('hate', 'Hate speech'), ('other', 'Other')], max_length=20),
        ),
    ]
