# Generated by Django 5.2.7 on 2025-12-16 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_options_alter_orderitem_options_and_more'),
        ('reviews', '0003_remove_videoreview_product_id_videoreview_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='videolike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='videosave',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='handled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam / Advertising'), ('nudity', 'Nudity or sexual content'), ('violence', 'Violence / Harmful content'), ('fraud', 'Fraud / Scam'), ('hate', 'Hate speech'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='review_product_id',
            field=models.CharField(blank=True, db_index=True, help_text='Matches OrderItem.review_product_id', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['slug'], name='reviews_has_slug_ce3ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['name'], name='reviews_has_name_eb8dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['follower', 'created_at'], name='reviews_use_followe_2396cb_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['following', 'created_at'], name='reviews_use_followi_d96eea_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['video', 'is_deleted', 'created_at'], name='reviews_vid_video_i_11a4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['user', 'created_at'], name='reviews_vid_user_id_6b963e_idx'),
        ),
        migrations.AddIndex(
            model_name='videolike',
            index=models.Index(fields=['video', 'created_at'], name='reviews_vid_video_i_1574bf_idx'),
        ),
        migrations.AddIndex(
            model_name='videolike',
            index=models.Index(fields=['user', 'created_at'], name='reviews_vid_user_id_4ff1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='videoreport',
            index=models.Index(fields=['video', 'created_at'], name='reviews_vid_video_i_42efdb_idx'),
        ),
        migrations.AddIndex(
            model_name='videoreport',
            index=models.Index(fields=['handled', 'created_at'], name='reviews_vid_handled_c0db83_idx'),
        ),
        migrations.AddIndex(
            model_name='videoreview',
            index=models.Index(fields=['-created_at'], name='reviews_vid_created_9cf882_idx'),
        ),
        migrations.AddIndex(
            model_name='videoreview',
            index=models.Index(fields=['user', '-created_at'], name='reviews_vid_user_id_57220d_idx'),
        ),
        migrations.AddIndex(
            model_name='videoreview',
            index=models.Index(fields=['is_public', 'is_deleted', 'is_approved', '-created_at'], name='reviews_vid_is_publ_4909e8_idx'),
        ),
        migrations.AddIndex(
            model_name='videosave',
            index=models.Index(fields=['video', 'created_at'], name='reviews_vid_video_i_dce7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='videosave',
            index=models.Index(fields=['user', 'created_at'], name='reviews_vid_user_id_573bad_idx'),
        ),
        migrations.AddIndex(
            model_name='videoview',
            index=models.Index(fields=['video', 'created_at'], name='reviews_vid_video_i_8276a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='uniq_follow_follower_following'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='no_self_follow'),
        ),
        migrations.AddConstraint(
            model_name='videolike',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='uniq_video_like_user_video'),
        ),
        migrations.AddConstraint(
            model_name='videosave',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='uniq_video_save_user_video'),
        ),
    ]
