# Generated by Django 5.2.7 on 2025-10-27 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone  # ✅ Added for proper default datetime handling


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(
                choices=[
                    ('Phones', 'Phones'),
                    ('Accessories', 'Accessories'),
                    ('Electronics', 'Electronics'),
                    ('Gadgets', 'Gadgets'),
                    ('Fashion', 'Fashion'),
                    ('Other', 'Other')
                ],
                default='Other',
                max_length=100
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now  # ✅ fixed default from 'exit' to timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
