# Generated by Django 5.2.7 on 2025-10-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_category_product_created_at_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.URLField(blank=True, null=True),
        ),
    ]
