# Generated by Django 5.2.7 on 2025-10-27 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_product_image4_product_image5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='If the item was sold through a partner, this links the reseller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartnerListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('resale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_listings', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_products', to='orders.product')),
            ],
        ),
    ]
