# Generated by Django 5.2.7 on 2025-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_partnerlisting_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlisting',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
