# Generated by Django 5.2.7 on 2025-11-08 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='If sold through a partner, links reseller to sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_order_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
