# Generated by Django 5.2.7 on 2025-11-08 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerlisting',
            old_name='resale_price',
            new_name='final_price',
        ),
        migrations.AddField(
            model_name='partnerlisting',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerlisting',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='partnerlisting',
            name='referral_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerlisting',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='If the item was sold through a partner, links reseller to sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_order_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
