# Generated by Django 5.2.7 on 2025-11-09 18:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_resale_price_partnerlisting_final_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerlisting',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Accumulates total confirmed profit from completed sales.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='If the item was sold through a partner referral link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_order_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
