# Generated by Django 5.2.7 on 2025-11-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_orderitem_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='review_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
