# Generated by Django 5.2.7 on 2025-11-28 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_review_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='review_product_id',
            field=models.CharField(blank=True, help_text='Identifier used by video reviews to link back to this item/product.', max_length=50, null=True),
        ),
    ]
