# Generated by Django 5.2.7 on 2025-11-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='review_product_id',
            field=models.CharField(blank=True, help_text='Stable ID used by the video review system', max_length=50, null=True),
        ),
    ]
